package: security
version: '0.1.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/security
requires:
    redaxo: '^5.15.1'
    php:
        version: '>=8.1, <9'
    packages:
        yform: '>=3.2,<5.0.0-dev'
        yrewrite: '^2.8'

page:
    title: 'translate:security_navi_title'
    perm: admin[]
    icon: rex-icon fa-group
    subpages:
        overview: { title: 'translate:security_overview' }
        fe_access: { title: 'translate:security_frontend_access' }
        error_notification: { title: 'translate:security_error_notification' }
        ip_access:
            title: 'translate:security_ip_access'
            table_name: rex_security_ip_access
        header:
            title: 'translate:security_header'
        checks:
            title: 'translate:security_checks'

pages:
    system/log/security_be_user:
        title: translate:security_be_user_log
        perm: admin

console_commands:
    security:ip_access: \FriendsOfRedaxo\Security\Command\IPAccess
    security:fe_access: \FriendsOfRedaxo\Security\Command\FrontendAccess

installer_ignore:
    - .git
    - .gitignore
    - .github
    - composer.json
    - .php-cs-fixer.dist.php
    - composer.lock

